### ISSUE TITLE
Procure better icon

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/ecr-integration#18]
Just want to track the change to get a good icon for this integration.

**Comment by jennstar121** [comment]
This is completed. SVG logo can be found [here in GDrive](https://drive.google.com/drive/folders/1ZD2BTPXEswUhAcLqcHA3DZ89MYUhtFQK?usp=sharing) (GitHub doesn't support SVG attachments, so I couldn't just attach here.)

I'm assigning to you @slimslenderslacks  and moving it to **Ready to Go** just so it's on your radar.

**Comment by slimslenderslacks** [comment]
@jennstar121 thanks!  I've updated with this commit:  https://github.com/atomist-skills/ecr-integration/commit/3a8ecaf3e3acf4feda840266c9541ce328f460f9
